[package]
name = "smt-strings"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.14.0"
pest = "2.7.15"
pest_derive = "2.7.15"
quickcheck = "1.0.3"
rand = "0.9.0"
smallvec = "1.14.0"


[dev-dependencies]
quickcheck_macros = "1"
