name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Format
      run: cargo fmt --all -- --check --verbose
    - name: Clippy
      run: cargo clippy --features=full -- -D warnings --verbose
    - name: Build
      run: cargo build --features=full --verbose
    - name: Run tests
      run: cargo test --features=full --verbose
